"""Write normalized inventory for Ansible consumption."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

import yaml

from orchestrator.inventory.models import NormalizedInventory


def write_normalized_yaml(inventory: NormalizedInventory, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = inventory.to_dict()
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    return path


def write_ansible_ini(inventory: NormalizedInventory, path: Path) -> Path:
    """Simple INI inventory: group 'monitored' with ansible_host=instance id for SSM."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by Lucidity orchestrator — do not edit by hand",
        f"# customer={inventory.customer_id} cloud={inventory.cloud_provider} "
        f"account={inventory.account_id} env={inventory.environment}",
        "",
        "[monitored]",
    ]
    for host in inventory.hosts:
        # For AWS SSM, ansible_host should be the instance id
        lines.append(
            f"{host.resource_id} ansible_host={host.resource_id} "
            f"ansible_connection=aws_ssm "
            f"private_ip={host.private_ip} "
            f"monitoring_profile={host.monitoring_profile} "
            f"customer={host.customer or inventory.customer_id} "
            f"environment={host.environment or inventory.environment}"
        )
    lines.append("")
    lines.append("[monitored:vars]")
    lines.append(f"aws_region={inventory.region}")
    lines.append(f"ansible_aws_ssm_region={inventory.region}")
    lines.append(f"customer_id={inventory.customer_id}")
    lines.append(f"monitoring_profile={inventory.monitoring_profile}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_summary_json(inventory: NormalizedInventory, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(inventory.to_dict(), indent=2), encoding="utf-8")
    return path


def load_yaml(path: Path) -> Dict[str, Any]:
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}
